package org.polaris2023.wild_wind.common.dyed;

import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;

import java.util.HashMap;
import java.util.Map;

public class DyedBlockMap {
    private static final Map<String, Map<DyeColor, Block>> dyedBlockMap = new HashMap<>();

    static {
        Map<DyeColor,Block> woolBlock = new HashMap<>();
        woolBlock.put(DyeColor.WHITE, Blocks.WHITE_WOOL);
        woolBlock.put(DyeColor.ORANGE, Blocks.ORANGE_WOOL);
        woolBlock.put(DyeColor.MAGENTA, Blocks.MAGENTA_WOOL);
        woolBlock.put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_WOOL);
        woolBlock.put(DyeColor.YELLOW, Blocks.YELLOW_WOOL);
        woolBlock.put(DyeColor.LIME, Blocks.LIME_WOOL);
        woolBlock.put(DyeColor.PINK, Blocks.PINK_WOOL);
        woolBlock.put(DyeColor.GRAY, Blocks.GRAY_WOOL);
        woolBlock.put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_WOOL);
        woolBlock.put(DyeColor.CYAN, Blocks.CYAN_WOOL);
        woolBlock.put(DyeColor.PURPLE, Blocks.PURPLE_WOOL);
        woolBlock.put(DyeColor.BLUE, Blocks.BLUE_WOOL);
        woolBlock.put(DyeColor.BROWN, Blocks.BROWN_WOOL);
        woolBlock.put(DyeColor.GREEN, Blocks.GREEN_WOOL);
        woolBlock.put(DyeColor.RED, Blocks.RED_WOOL);
        woolBlock.put(DyeColor.BLACK, Blocks.BLACK_WOOL);
        dyedBlockMap.put("WOOL", woolBlock);
        Map<DyeColor, Block> carpetBlock= new HashMap<>();
        carpetBlock.put(DyeColor.BLACK, Blocks.BLACK_CARPET);
        carpetBlock.put(DyeColor.BLUE, Blocks.BLUE_CARPET);
        carpetBlock.put(DyeColor.BROWN, Blocks.BROWN_CARPET);
        carpetBlock.put(DyeColor.CYAN, Blocks.CYAN_CARPET);
        carpetBlock.put(DyeColor.GRAY, Blocks.GRAY_CARPET);
        carpetBlock.put(DyeColor.GREEN, Blocks.GREEN_CARPET);
        carpetBlock.put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_CARPET);
        carpetBlock.put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_CARPET);
        carpetBlock.put(DyeColor.LIME, Blocks.LIME_CARPET);
        carpetBlock.put(DyeColor.MAGENTA, Blocks.MAGENTA_CARPET);
        carpetBlock.put(DyeColor.ORANGE, Blocks.ORANGE_CARPET);
        carpetBlock.put(DyeColor.PINK, Blocks.PINK_CARPET);
        carpetBlock.put(DyeColor.PURPLE, Blocks.PURPLE_CARPET);
        carpetBlock.put(DyeColor.RED, Blocks.RED_CARPET);
        carpetBlock.put(DyeColor.WHITE, Blocks.WHITE_CARPET);
        carpetBlock.put(DyeColor.YELLOW, Blocks.YELLOW_CARPET);
        dyedBlockMap.put("CARPET", carpetBlock);
        Map<DyeColor, Block> terracottaBlock= new HashMap<>();
        terracottaBlock.put(DyeColor.BLACK, Blocks.BLACK_TERRACOTTA);
        terracottaBlock.put(DyeColor.BLUE, Blocks.BLUE_TERRACOTTA);
        terracottaBlock.put(DyeColor.BROWN, Blocks.BROWN_TERRACOTTA);
        terracottaBlock.put(DyeColor.CYAN, Blocks.CYAN_TERRACOTTA);
        terracottaBlock.put(DyeColor.GRAY, Blocks.GRAY_TERRACOTTA);
        terracottaBlock.put(DyeColor.GREEN, Blocks.GREEN_TERRACOTTA);
        terracottaBlock.put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_TERRACOTTA);
        terracottaBlock.put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_TERRACOTTA);
        terracottaBlock.put(DyeColor.LIME, Blocks.LIME_TERRACOTTA);
        terracottaBlock.put(DyeColor.MAGENTA, Blocks.MAGENTA_TERRACOTTA);
        terracottaBlock.put(DyeColor.ORANGE, Blocks.ORANGE_TERRACOTTA);
        terracottaBlock.put(DyeColor.PINK, Blocks.PINK_TERRACOTTA);
        terracottaBlock.put(DyeColor.PURPLE, Blocks.PURPLE_TERRACOTTA);
        terracottaBlock.put(DyeColor.RED, Blocks.RED_TERRACOTTA);
        terracottaBlock.put(DyeColor.WHITE, Blocks.WHITE_TERRACOTTA);
        terracottaBlock.put(DyeColor.YELLOW, Blocks.YELLOW_TERRACOTTA);
        dyedBlockMap.put("TERRACOTTA", terracottaBlock);
        Map<DyeColor, Block> bedBlock= new HashMap<>();
        bedBlock.put(DyeColor.BLACK, Blocks.BLACK_BED);
        bedBlock.put(DyeColor.BLUE, Blocks.BLUE_BED);
        bedBlock.put(DyeColor.BROWN, Blocks.BROWN_BED);
        bedBlock.put(DyeColor.CYAN, Blocks.CYAN_BED);
        bedBlock.put(DyeColor.GRAY, Blocks.GRAY_BED);
        bedBlock.put(DyeColor.GREEN, Blocks.GREEN_BED);
        bedBlock.put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_BED);
        bedBlock.put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_BED);
        bedBlock.put(DyeColor.LIME, Blocks.LIME_BED);
        bedBlock.put(DyeColor.MAGENTA, Blocks.MAGENTA_BED);
        bedBlock.put(DyeColor.ORANGE, Blocks.ORANGE_BED);
        bedBlock.put(DyeColor.PINK, Blocks.PINK_BED);
        bedBlock.put(DyeColor.PURPLE, Blocks.PURPLE_BED);
        bedBlock.put(DyeColor.RED, Blocks.RED_BED);
        bedBlock.put(DyeColor.WHITE, Blocks.WHITE_BED);
        bedBlock.put(DyeColor.YELLOW, Blocks.YELLOW_BED);
        dyedBlockMap.put("BED", bedBlock);
        Map<DyeColor, Block> concreteBlock= new HashMap<>();
        concreteBlock.put(DyeColor.BLACK, Blocks.BLACK_CONCRETE);
        concreteBlock.put(DyeColor.BLUE, Blocks.BLUE_CONCRETE);
        concreteBlock.put(DyeColor.BROWN, Blocks.BROWN_CONCRETE);
        concreteBlock.put(DyeColor.CYAN, Blocks.CYAN_CONCRETE);
        concreteBlock.put(DyeColor.GRAY, Blocks.GRAY_CONCRETE);
        concreteBlock.put(DyeColor.GREEN, Blocks.GREEN_CONCRETE);
        concreteBlock.put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_CONCRETE);
        concreteBlock.put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_CONCRETE);
        concreteBlock.put(DyeColor.LIME, Blocks.LIME_CONCRETE);
        concreteBlock.put(DyeColor.MAGENTA, Blocks.MAGENTA_CONCRETE);
        concreteBlock.put(DyeColor.ORANGE, Blocks.ORANGE_CONCRETE);
        concreteBlock.put(DyeColor.PINK, Blocks.PINK_CONCRETE);
        concreteBlock.put(DyeColor.PURPLE, Blocks.PURPLE_CONCRETE);
        concreteBlock.put(DyeColor.RED, Blocks.RED_CONCRETE);
        concreteBlock.put(DyeColor.WHITE, Blocks.WHITE_CONCRETE);
        concreteBlock.put(DyeColor.YELLOW, Blocks.YELLOW_CONCRETE);
        dyedBlockMap.put("CONCRETE", concreteBlock);
        Map<DyeColor, Block> concrete_powderBlock= new HashMap<>();
        concrete_powderBlock.put(DyeColor.BLACK, Blocks.BLACK_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.BLUE, Blocks.BLUE_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.BROWN, Blocks.BROWN_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.CYAN, Blocks.CYAN_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.GRAY, Blocks.GRAY_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.GREEN, Blocks.GREEN_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.LIME, Blocks.LIME_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.MAGENTA, Blocks.MAGENTA_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.ORANGE, Blocks.ORANGE_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.PINK, Blocks.PINK_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.PURPLE, Blocks.PURPLE_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.RED, Blocks.RED_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.WHITE, Blocks.WHITE_CONCRETE_POWDER);
        concrete_powderBlock.put(DyeColor.YELLOW, Blocks.YELLOW_CONCRETE_POWDER);
        dyedBlockMap.put("CONCRETE_POWDER", concrete_powderBlock);
        Map<DyeColor, Block> glazed_terracottaBlock= new HashMap<>();
        glazed_terracottaBlock.put(DyeColor.BLACK, Blocks.BLACK_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.BLUE, Blocks.BLUE_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.BROWN, Blocks.BROWN_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.CYAN, Blocks.CYAN_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.GRAY, Blocks.GRAY_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.GREEN, Blocks.GREEN_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.LIME, Blocks.LIME_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.MAGENTA, Blocks.MAGENTA_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.ORANGE, Blocks.ORANGE_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.PINK, Blocks.PINK_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.PURPLE, Blocks.PURPLE_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.RED, Blocks.RED_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.WHITE, Blocks.WHITE_GLAZED_TERRACOTTA);
        glazed_terracottaBlock.put(DyeColor.YELLOW, Blocks.YELLOW_GLAZED_TERRACOTTA);
        dyedBlockMap.put("GLAZED_TERRACOTTA", glazed_terracottaBlock);
        Map<DyeColor, Block> glassBlock= new HashMap<>();
        glassBlock.put(DyeColor.BLACK, Blocks.BLACK_STAINED_GLASS);
        glassBlock.put(DyeColor.BLUE, Blocks.BLUE_STAINED_GLASS);
        glassBlock.put(DyeColor.BROWN, Blocks.BROWN_STAINED_GLASS);
        glassBlock.put(DyeColor.CYAN, Blocks.CYAN_STAINED_GLASS);
        glassBlock.put(DyeColor.GRAY, Blocks.GRAY_STAINED_GLASS);
        glassBlock.put(DyeColor.GREEN, Blocks.GREEN_STAINED_GLASS);
        glassBlock.put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_STAINED_GLASS);
        glassBlock.put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_STAINED_GLASS);
        glassBlock.put(DyeColor.LIME, Blocks.LIME_STAINED_GLASS);
        glassBlock.put(DyeColor.MAGENTA, Blocks.MAGENTA_STAINED_GLASS);
        glassBlock.put(DyeColor.ORANGE, Blocks.ORANGE_STAINED_GLASS);
        glassBlock.put(DyeColor.PINK, Blocks.PINK_STAINED_GLASS);
        glassBlock.put(DyeColor.PURPLE, Blocks.PURPLE_STAINED_GLASS);
        glassBlock.put(DyeColor.RED, Blocks.RED_STAINED_GLASS);
        glassBlock.put(DyeColor.WHITE, Blocks.WHITE_STAINED_GLASS);
        glassBlock.put(DyeColor.YELLOW, Blocks.YELLOW_STAINED_GLASS);
        dyedBlockMap.put("GLASS", glassBlock);
        Map<DyeColor, Block> glass_paneBlock= new HashMap<>();
        glass_paneBlock.put(DyeColor.BLACK, Blocks.BLACK_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.BLUE, Blocks.BLUE_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.BROWN, Blocks.BROWN_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.CYAN, Blocks.CYAN_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.GRAY, Blocks.GRAY_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.GREEN, Blocks.GREEN_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.LIME, Blocks.LIME_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.MAGENTA, Blocks.MAGENTA_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.ORANGE, Blocks.ORANGE_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.PINK, Blocks.PINK_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.PURPLE, Blocks.PURPLE_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.RED, Blocks.RED_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.WHITE, Blocks.WHITE_STAINED_GLASS_PANE);
        glass_paneBlock.put(DyeColor.YELLOW, Blocks.YELLOW_STAINED_GLASS_PANE);
        dyedBlockMap.put("GLASS_PANE", glass_paneBlock);
        Map<DyeColor, Block> shulker_boxBlock= new HashMap<>();
        shulker_boxBlock.put(DyeColor.BLACK, Blocks.BLACK_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.BLUE, Blocks.BLUE_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.BROWN, Blocks.BROWN_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.CYAN, Blocks.CYAN_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.GRAY, Blocks.GRAY_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.GREEN, Blocks.GREEN_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.LIME, Blocks.LIME_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.MAGENTA, Blocks.MAGENTA_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.ORANGE, Blocks.ORANGE_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.PINK, Blocks.PINK_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.PURPLE, Blocks.PURPLE_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.RED, Blocks.RED_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.WHITE, Blocks.WHITE_SHULKER_BOX);
        shulker_boxBlock.put(DyeColor.YELLOW, Blocks.YELLOW_SHULKER_BOX);
        dyedBlockMap.put("SHULKER_BOX", shulker_boxBlock);
        Map<DyeColor, Block> candleBlock= new HashMap<>();
        candleBlock.put(DyeColor.BLACK, Blocks.BLACK_CANDLE);
        candleBlock.put(DyeColor.BLUE, Blocks.BLUE_CANDLE);
        candleBlock.put(DyeColor.BROWN, Blocks.BROWN_CANDLE);
        candleBlock.put(DyeColor.CYAN, Blocks.CYAN_CANDLE);
        candleBlock.put(DyeColor.GRAY, Blocks.GRAY_CANDLE);
        candleBlock.put(DyeColor.GREEN, Blocks.GREEN_CANDLE);
        candleBlock.put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_CANDLE);
        candleBlock.put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_CANDLE);
        candleBlock.put(DyeColor.LIME, Blocks.LIME_CANDLE);
        candleBlock.put(DyeColor.MAGENTA, Blocks.MAGENTA_CANDLE);
        candleBlock.put(DyeColor.ORANGE, Blocks.ORANGE_CANDLE);
        candleBlock.put(DyeColor.PINK, Blocks.PINK_CANDLE);
        candleBlock.put(DyeColor.PURPLE, Blocks.PURPLE_CANDLE);
        candleBlock.put(DyeColor.RED, Blocks.RED_CANDLE);
        candleBlock.put(DyeColor.WHITE, Blocks.WHITE_CANDLE);
        candleBlock.put(DyeColor.YELLOW, Blocks.YELLOW_CANDLE);
        dyedBlockMap.put("CANDLE", candleBlock);
        Map<DyeColor, Block> bannerBlock= new HashMap<>();
        bannerBlock.put(DyeColor.BLACK, Blocks.BLACK_BANNER);
        bannerBlock.put(DyeColor.BLUE, Blocks.BLUE_BANNER);
        bannerBlock.put(DyeColor.BROWN, Blocks.BROWN_BANNER);
        bannerBlock.put(DyeColor.CYAN, Blocks.CYAN_BANNER);
        bannerBlock.put(DyeColor.GRAY, Blocks.GRAY_BANNER);
        bannerBlock.put(DyeColor.GREEN, Blocks.GREEN_BANNER);
        bannerBlock.put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_BANNER);
        bannerBlock.put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_BANNER);
        bannerBlock.put(DyeColor.LIME, Blocks.LIME_BANNER);
        bannerBlock.put(DyeColor.MAGENTA, Blocks.MAGENTA_BANNER);
        bannerBlock.put(DyeColor.ORANGE, Blocks.ORANGE_BANNER);
        bannerBlock.put(DyeColor.PINK, Blocks.PINK_BANNER);
        bannerBlock.put(DyeColor.PURPLE, Blocks.PURPLE_BANNER);
        bannerBlock.put(DyeColor.RED, Blocks.RED_BANNER);
        bannerBlock.put(DyeColor.WHITE, Blocks.WHITE_BANNER);
        bannerBlock.put(DyeColor.YELLOW, Blocks.YELLOW_BANNER);
        dyedBlockMap.put("BANNER", bannerBlock);

    }
    public Map<DyeColor,Block> getDyedBlock(String type){
        return dyedBlockMap.get(type);
    }
}