modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="wild_wind"
version="1.0.0"
displayName="Wild Wind Mod"
authors="wdog5734,baka4n,Viola-Siemens"
description='''Wild Wind Mod'''

[[mixins]]
config="wild_wind.mixins.json"

[[dependencies.wild_wind]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.wild_wind]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
