[versions]
geckolib-version="4.6.6"
terrablender-version="1.21.1-4.1.0.4"
jar-in-jar-names="geckolib-neoforge,"

[libraries]
geckolib-neoforge={group = "software.bernie.geckolib", name = "geckolib-neoforge-1.21.1", version.ref = "geckolib-version"}
terrablender-neoforge={group = "com.github.glitchfiend", name = "TerraBlender-neoforge", version.ref = "terrablender-version"}

[bundles]
jar-in-jar=["geckolib-neoforge"]
linkage=["terrablender-neoforge"]