[versions]
geckolib-version="4.6.6"
jar-in-jar-names="geckolib-neoforge,"

[libraries]
geckolib-neoforge={group = "software.bernie.geckolib", name = "geckolib-neoforge-1.21.1", version.ref = "geckolib-version"}

[bundles]
jar-in-jar=["geckolib-neoforge"]
linkage=[]