[versions]
terrablender-version="1.21.1-4.1.0.4"
eye-lib-version="21.1.3"

[libraries]
terrablender-neoforge={group = "com.github.glitchfiend", name = "TerraBlender-neoforge", version.ref="terrablender-version"}
eye-lib-neoforge={group = "io.github.tt432", name = "eyelib", version.ref="eye-lib-version"}
[bundles]
jar-in-jar=["eye-lib-neoforge"]
linkage=["terrablender-neoforge"]