package org.polaris2023.wild_wind.datagen.custom;

import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.neoforge.client.model.generators.BlockModelProvider;
import net.neoforged.neoforge.client.model.generators.BlockStateProvider;
import net.neoforged.neoforge.client.model.generators.ItemModelProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;

import java.util.concurrent.CompletableFuture;

/**
 * @author : baka4n
 * {@code @Date : 2025/03/18 19:09:04}
 */
public class WildWindClientProvider implements DataProvider {

    final BlockStateProvider stateProvider;
    final BlockModelProvider blockModelProvider;
    final ItemModelProvider itemModelProvider;
    final String modid;

    public void init() {

    }// 不可在此处写代码，切记

    public static WildWindClientProvider getInstance(PackOutput output, String modid, ExistingFileHelper exFileHelper) {
        return new WildWindClientProvider(output, modid, exFileHelper);
    }


    public WildWindClientProvider(PackOutput output, String modid, ExistingFileHelper exFileHelper) {
        this.modid = modid;
        this.stateProvider = new BlockStateProvider(output, modid, exFileHelper) {

            @Override
            protected void registerStatesAndModels() {
                init();
            }
        };
        itemModelProvider = stateProvider.itemModels();
        blockModelProvider = stateProvider.models();

    }

    @Override
    public CompletableFuture<?> run(CachedOutput cachedOutput) {

        return CompletableFuture.allOf(
                stateProvider.run(cachedOutput)
        );
    }

    @Override
    public String getName() {
        return "Model Generated By " + modid;
    }
}
