# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Release

on : [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Set version env
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Datagen with gradle
        run: ./gradlew runData
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Server Gradle
        run: |
          ./gradlew runServer
          stop

      - name: Upload binaries to release
        uses: actions/upload-artifact@v4
        with:
          name: wild_wind-1.0.0.jar
          path: build/libs/wild_wind-1.0.0.jar
          repo-token:  ${{ secrets.ACTION_TOKEN }}