# make by baka4n

name: Cleanuo Old Workflow Runs
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old workflow runs
        uses: actions/github-script@v7
        with:
          script: |
            // 获取build yml
            const { data: workflow } = await github.rest.actions.getWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
              workflow_id: 'build.yml',
            });
            // 获取条目
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow.id,
              per_page: 100
            });
            // 计算 10 天前的日期
            const cutoffDate = new Date();
            cutoffDate.setDate(cutoffDate.getDate() - 10);
            
            // 遍历删除
            for(const run of runs.workflow_runs) {
              if(new Date(run.created_at) < cutoffDate) {
                await github.rest.actions.deleteWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id,
                });
                console.log(`✅ Deleted 'build' run #${run.id} (created at ${run.created_at})
              }
            }